language: python
python:
- '3.8'
before_install:
- export PYTHONPATH=$PYTHONPATH:$(pwd)
install:
- pip install -r requirements.txt
- pip install git+git://github.com/meraki-analytics/cassiopeia.git
- pip install codecov
- pip install tox-travis
- pip install pytest
- pip freeze
script:
- tox
after_success:
- codecov
deploy:
  provider: pypi
  user: __token__
  password:
    secure: VUvUbdSonPVDHMYp4TQATTUIGjFxGV446vU2WHIv2/Y1Fds63LvHjKgnFwdkKcwwiru3l391+H4GSOq11WvSUP32+4r9bN/G/z2Ed9U0S9glfBNHtZt8V83tZmrCh2NM43KqHwplkC8X8TUuhxr7WtL6/OKCVwDr+GOBSOnhZ3+dIbjYXJ40Ripy8bd9keyplzpDd2pkgg2YzBieEVq1NYmr6XHqjvwxo65C5vSIaqKVH7hk/h0oCsqLFg0jPttGN2eu/0KKSTaXzXMbwzEz+t9THy5rv01vCFpFmT4uacIw18nogDiyl94S1AAIbE77LAkf+n7TYAu5GCqEY3sufL0KCNzYohod4C0gXgXvON9Gn7A0VBoRUGF5l9qTl1hvKtfMcPGEBtMYUv4BACAcJf0yhykHuI01wibyU4un5wXSQ7vESU7B7nfn1Kgl9Fw4NZ7QA4VgS5Ivamv6ffH3BhosMrtFH3xt2FcMQjTup4WUonnNsjlWiYZ5MDAeflJtGS4LTkFVVyeX4pAPXC8KABZcYNcJZl2hT5AkFiqLO2No2C73PcO2b8xycnlo5R9+0EIorL8cqFkVcgcMfXaAIAbhNAsnkVodEKbPfiV/YQ4iU4mZXnMimj7YgO8auGO8OczeLPrWGuCWhrf9Hajv/ni4wwY4Sl5qqvNKQRusHdc=
  distributions: sdist bdist_wheel --universal
  skip_existing: true
  on:
    branch: master
